apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "m13k.fullname" . }}-mutate
  labels:
    {{- include "m13k.labels" . | nindent 4 }}
data:
  ytt.yaml: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:template", "template")

    #@overlay/match by=overlay.subset({"kind": "Secret"})
    ---
    metadata:
      #@overlay/match missing_ok=True
      labels:
        #@overlay/match missing_ok=True
        m13k: "true"