{{- if not .Values.certManager.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "m13k.fullname" . }}-tls
  labels:
    {{- include "m13k.labels" . | nindent 4 }}
type: tls
data:
  server.crt: {{ .Files.Get "files/cert.pem" | b64enc }}
  server.key: {{ .Files.Get "files/key.pem" | b64enc }}
{{- end -}}